version: 2
updates:
  - package-ecosystem: pip
    directory: "/requirements"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    reviewers:
      - "Doist/backend"
    commit-message:
      prefix: "chore(deps):"
